"""add published column

Revision ID: ed32d940284f
Revises: 9b1b6e7bae4c
Create Date: 2026-07-22 14:37:21.663317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed32d940284f'
down_revision: Union[str, Sequence[str], None] = '9b1b6e7bae4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('published', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('posts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
    "fk_posts_user_id_users",
    "posts",
    "users",
    ["user_id"],
    ["id"],
    ondelete="CASCADE"
)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "posts_user_id_fkey",
        "posts",
        type_="foreignkey"
    )

    op.drop_column("posts", "user_id")
    op.drop_column("posts", "created_at")
    op.drop_column("posts", "published")
    op.drop_column("posts", "content")

    op.drop_table("votes")
    op.drop_table("users")
    # ### end Alembic commands ###
